## Assignmnet 3

In [2]:
#Task1 Q1
x,y=map(int,input().split())
while True:
    try:
        if y==0:
            raise e
    except Exception as e:
        print("You cant divide by 0")
        break
    else:
        print(x/y)
        print("Please try again")
        break

4 0
You cant divide by 0


In [21]:
#Task1 Q2
subject=["Americans","Indians"]
objects=["Baseball","Cricket"]
verb=["Play","watch"]

[i+" "+j+" "+k for i in subject for j in verb for k in objects]


['Americans Play Baseball',
 'Americans Play Cricket',
 'Americans watch Baseball',
 'Americans watch Cricket',
 'Indians Play Baseball',
 'Indians Play Cricket',
 'Indians watch Baseball',
 'Indians watch Cricket']

In [18]:
#Task2 
import numpy as np

'''Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
an intermediate vector. Use diff order formula based on increasing and decreasing condition.
Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix''' 
   
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

print("---------Vander matrix---------")

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix",no_col_opmat,"\n")
print("Vander matrix in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix in increasing order of powers:\n\n",op_matx_inc_order,"\n")

---------Vander matrix---------
The input array is: [1 2 3 4 5] 

Number of columns in output matrix 3 

Vander matrix in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

